replicas: 1

automountServiceAccountToken: false

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 250m
    memory: 256Mi

persistence:
  enabled: false

datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        url: http://prometheus-server.observability.svc.cluster.local
        access: proxy
        isDefault: true

      - name: Tempo
        type: tempo
        url: http://tempo.observability.svc.cluster.local
        access: proxy

      - name: Loki
        type: loki
        url: http://loki.observability.svc.cluster.local
        access: proxy
