server:
  replicaCount: 1

  retention: "3d"

  resources:
    requests:
      cpu: 250m
      memory: 512Mi
    limits:
      cpu: 500m
      memory: 1Gi

alertmanager:
  enabled: true


extraScrapeConfigs: |
  - job_name: 'otel-demo'
    kubernetes_sd_configs:
      - role: endpoints
    relabel_configs:
      - source_labels: [__meta_kubernetes_namespace]
        action: keep
        regex: otel-demo
      - source_labels: [__meta_kubernetes_endpoint_port_name]
        action: keep
        regex: prometheus
  
  - job_name: 'otel-collector'
    kubernetes_sd_configs:
      - role: endpoints
    relabel_configs:
      - source_labels: [__meta_kubernetes_namespace]
        action: keep
        regex: observability
      - source_labels: [__meta_kubernetes_service_name]
        action: keep
        regex: otel-collector
      - source_labels: [__meta_kubernetes_endpoint_port_name]
        action: keep
        regex: metrics
