default:
  envOverrides:
    - name: OTEL_COLLECTOR_NAME
      value: otel-collector.observability.svc.cluster.local

opentelemetry-collector:
  enabled: false

jaeger:
  enabled: false

prometheus:
  enabled: false

grafana:
  enabled: false

opensearch:
  enabled: false
